apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

android {
  namespace "expo.modules.echowalksonar"
  compileSdkVersion safeExtGet("compileSdkVersion", 36)
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
  }
}
